<h1>List of stories</h1>
<table class="table table-striped">
    <thead>
        <tr><th>Name</th><th>Description</th><th>Status</th><th></th></tr>
    </thead>
    <?php foreach ($this->listStories AS $story): ?>
        <tr><td><?= $story->name; ?></td><td><?= $story->description; ?></td><td><?= $story->status; ?></td><td><a href="<?= $this->basePath() ?>">Détail</a></td></tr>
        <?php
    endforeach;
    ?>
    <tfoot>
        <tr><td colspan="3"><a href="<?= $this->basePath() ?>/scrum/story/add" class="btn btn-primary">Add a project</a></td></tr>
    </tfoot>
</table>