<h1>List of projects</h1>
<table class="table table-striped">
    <thead>
        <tr><th>Name</th><th>Description</th><th></th></tr>
    </thead>
    <?php foreach ($this->listProjects AS $project): ?>
        <tr><td><?= $project->name; ?></td><td><?= $project->description; ?></td><td><a href="<?= $this->basePath() ?>/scrum/project/detail/<?= $project->id_project ?>">Détail</a></td></tr>
        <?php
    endforeach;
    ?>
    <tfoot>
        <tr><td colspan="3"><a href="<?= $this->basePath() ?>/scrum/project/add" class="btn btn-primary">Add a project</a></td></tr>
    </tfoot>
</table>