<?php

$sprintDetails = $this->sprintDetails;
$linkForm = $this->linkForm;

?>
<a href="<?= $this->basePath() ?>/scrum/project/detail/<?= $sprintDetails->fk_id_project ?>">Back to Project</a>
<h1>Sprint : <?= $sprintDetails->name ?><a class="btn" href="<?= $this->basePath() . "/scrum/sprint/edit/" . $sprintDetails->id_sprint ?>">Edit</a></h1>
<span>From <?= $sprintDetails->start_date ?> to <?= $sprintDetails->end_date ?></span>
<h2>List of stories</h2>
<table class="table table-striped">
    <thead>
        <tr><th><th>Name</th><th>Description</th><th>Status</th><th></th></tr>
    </thead>
    <?php foreach ($this->listStories AS $story): ?>
        <tr><td><img src="http://www.wunderbites.co.nz/images/icon-story.png"></td><td><?= $story->name; ?></td><td><?= $story->description; ?></td><td><?= $story->status; ?></td><td><a href="<?= $this->basePath() ?>/scrum/story/detail/<?= $story->id_story ?>">Détail</a></td></tr>
        <?php
    endforeach;
    ?>
    <tfoot>
        <tr><td colspan="5">
                <?= $this->form()->openTag($linkForm) ?>
                <?= $this->formRow($linkForm->get("fk_id_story")); ?>
                <?= $this->formRow($linkForm->get("submit")); ?>
                <?= $this->form()->closeTag() ?>
    </tfoot>
</table>