<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Scrum4Free')->setAutoEscape(false) ?>

        <!-- Le styles -->
        
        <?php /*echo $this->headLink(array(
            'rel' => 'shortcut icon', 
            'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath() . '/images/favicon.ico'
            ))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')*/ ?>
        
        <link href="twitter-bootstrap/less/bootstrap.less" rel="stylesheet/less">
        <script src="less-1.3.0.min.js"></script>
        
        <!-- Scripts -->
        <?php /*echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')*/ ?>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
        <script src="http://code.jquery.com/ui/1.8.24/jquery-ui.min.js" type="text/javascript"></script>
        
        <script src="jquery.livequery.js"></script>
        
        <script src="general.js"></script>
        
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand" href="#">Scrum4free</a>
                    <ul class="nav">
                        <li class="active"><a href="#">Scrum</a></li>
                    </ul>
                </div>
            </div>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
