<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Scrum4Free')->setAutoEscape(false) ?>
        
        <link href="<?php echo $this->basePath(); ?>/twitter-bootstrap/less/bootstrap.less" rel="stylesheet/less">
        <script src="<?php echo $this->basePath(); ?>/less-1.3.0.min.js"></script>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
        <script src="http://code.jquery.com/ui/1.8.24/jquery-ui.min.js" type="text/javascript"></script>
        
        <script src="<?php echo $this->basePath(); ?>/jquery.livequery.js"></script>
        
        <script src="<?php echo $this->basePath(); ?>/general.js"></script>
        
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand" href="#">Scrum4free</a>
                    <ul class="nav">
                        <li><a href="<?= $this->basePath() ?>/scrum/project/list">Projects</a></li>
<!--                        <li><a href="<?= $this->basePath() ?>/scrum/story/list">Stories</a></li>
                        <li><a href="<?= $this->basePath() ?>/scrum/sprint/list">Sprints</a></li>-->
                    </ul>
                </div>
            </div>
            <?php 
            echo $this->navigation("navigation")->breadCrumbs();
            echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>