<h1>List of tasks</h1>
<table class="table table-striped">
    <thead>
        <tr><th>Name</th><th>Description</th><th>Status</th><th></th></tr>
    </thead>
    <?php foreach ($this->listTasks AS $task): ?>
        <tr>
            <td><?= $task->name; ?></td>
            <td><?= $task->description; ?></td>
            <td><?= $task->status; ?></td>
            <td><?= $task->time; ?></td>
            <td><?= $task->actors; ?></td>
            <td><a href="<?= $this->basePath() ?>">Détail</a></td>
        </tr>
        <?php
    endforeach;
    ?>
</table>